import { FAQItem } from '@/lib/faq-search';

// Car Finance FAQs
export const carFinanceFaqs: FAQItem[] = [
  {
    id: 'finance-1',
    question: 'What types of car finance are available in the UK?',
    answer: 'In the UK, the main car finance options include: Personal Contract Purchase (PCP), which involves an initial deposit, monthly payments, and a final balloon payment if you wish to own the vehicle at the end of the term; Hire Purchase (HP), where you pay a deposit followed by fixed monthly payments until you own the car outright; Personal Contract Hire (PCH) or leasing, which functions as a long-term rental with no option to purchase; Personal Loans from banks or building societies, which provide funds to purchase the vehicle outright while you repay the loan; and 0% Finance deals occasionally offered by manufacturers, allowing interest-free repayments over a fixed term. Each option has distinct advantages regarding deposit requirements, monthly payment amounts, ownership paths, mileage restrictions, and end-of-term flexibility. Your choice should align with your financial situation, usage patterns, and whether long-term ownership is your goal.'
  },
  {
    id: 'finance-2',
    question: 'How does PCP (Personal Contract Purchase) car finance work?',
    answer: 'PCP financing begins with an initial deposit (typically 10-15% of the vehicle\'s value), followed by fixed monthly payments over an agreed term (usually 24-48 months). These payments cover the vehicle\'s depreciation rather than its full value, making them lower than traditional hire purchase payments. At the end of the term, you have three options: pay the pre-determined Guaranteed Minimum Future Value (GMFV or "balloon payment") to own the car; return the vehicle with nothing more to pay (provided you\'ve adhered to agreed mileage limits and maintained the car properly); or trade in any equity (if the car\'s actual value exceeds the GMFV) toward a new vehicle on a fresh PCP agreement. Throughout the agreement, you don\'t legally own the vehicle until the final payment is made. PCP suits those who enjoy regularly changing vehicles, prefer lower monthly payments, and want flexibility at the end of the agreement. However, you must adhere to mileage restrictions (excess mileage charges apply) and maintain the vehicle to manufacturer-recommended standards.'
  },
  {
    id: 'finance-3',
    question: 'What is Hire Purchase (HP) car finance?',
    answer: 'Hire Purchase (HP) is a straightforward car finance method where you pay an initial deposit (typically 10%) followed by fixed monthly payments over an agreed term, usually 1-5 years. Unlike PCP, there\'s no balloon payment at the end, and the monthly payments cover the entire vehicle cost plus interest, making them higher than equivalent PCP payments. You don\'t legally own the car until the final payment is made—the finance company remains the legal owner until then. HP offers several advantages: no mileage restrictions; predictable, fixed payments; automatic ownership once payments are completed; often simpler early settlement terms than PCP; and suitability for vehicles that depreciate quickly or older cars where future value is uncertain. HP is particularly appropriate if you plan to keep the vehicle long-term, prefer ownership rather than regular upgrades, or want to avoid mileage restrictions. The process typically requires a credit check, and missed payments can result in repossession until you\'ve paid more than one-third of the total amount, after which a court order is required.'
  },
  {
    id: 'finance-4',
    question: 'What documentation do I need for car finance approval?',
    answer: 'For car finance approval in the UK, you\'ll typically need to provide: proof of identity (passport or driving licence); proof of address (recent utility bills or bank statements from the past three months); evidence of income (recent payslips, bank statements showing income, or tax returns for self-employed applicants); employment details (employer name, address, contact information, and employment history for typically 3+ years); banking information (usually account number and sort code for payment setup); and comprehensive details about the vehicle you intend to purchase (registration, make, model, year, and dealer information). Additional documentation may include proof of deposit, proof of UK residency status for non-UK citizens, and details of existing financial commitments. Preparation is key—having these documents readily available can expedite the application process and increase approval chances. Most lenders now offer online application systems where documentation can be uploaded electronically, though traditional paper-based applications remain available at dealerships.'
  },
  {
    id: 'finance-5',
    question: 'Can I get car finance with bad credit?',
    answer: 'Yes, car finance with bad credit is possible, though it comes with certain limitations. Specialised lenders cater to this market but typically charge higher interest rates (often 15-30% APR compared to 3-10% for good credit applicants) to offset the increased risk. You\'ll likely need a larger deposit (20-30% versus 10% with good credit) and may face restrictions on vehicle age and value. To improve your chances, thoroughly check your credit reports for errors, provide proof of stable income and address history, save for a larger deposit, consider a guarantor if possible, avoid multiple applications that trigger hard credit checks, and be realistic about affordable vehicles. Starting with your current bank can be advantageous if you maintain a good banking relationship. While approval odds increase with sub-prime specialists, be cautious of excessively high interest rates—sometimes waiting 6-12 months while actively rebuilding your credit score can result in significantly better terms. Remember that making timely payments on car finance can help rebuild your credit profile over time.'
  },
  {
    id: 'finance-6',
    question: 'How can I get out of a car finance agreement early?',
    answer: 'To exit a car finance agreement early, request a settlement figure from your lender, which represents the remaining balance plus any early termination fees. You can then pay this amount in full, effectively ending the agreement. Alternatively, if you\'ve paid at least 50% of the total amount payable on HP or PCP agreements, you may utilize Voluntary Termination rights under the Consumer Credit Act 1974, returning the vehicle without further obligation (though excess mileage or damage charges may apply). For those unable to pay the settlement figure, options include selling the car privately (if the sale price covers the settlement figure) or part-exchanging for a less expensive vehicle, using any equity to settle the existing finance. Some agreements offer refinancing to extend the term and reduce monthly payments, though this increases the total cost. If facing financial difficulties, contact your lender promptly—they may offer payment holidays or reduced payments temporarily. As a last resort, voluntary surrender returns the vehicle to the lender, but the outstanding balance after the car\'s sale remains your responsibility and will damage your credit score.'
  },
  {
    id: 'finance-7',
    question: 'Should I choose dealer finance or a bank loan?',
    answer: 'Dealer finance offers convenience (one-stop shopping for vehicle and financing), potential manufacturer subsidies (including deposit contributions and lower interest rates), greater flexibility at the end of PCP agreements, and simplified approval processes—often with instant decisions. However, bank loans provide complete ownership from purchase, no mileage restrictions or condition penalties, potentially lower interest rates for those with excellent credit, no penalty for early repayment, and the negotiating power of being a "cash buyer" at dealerships. When deciding, consider your priorities: lower monthly payments typically favor dealer PCP options, while lower total cost and immediate ownership favor bank loans. Compare APRs after negotiating dealer rates (they often have margin to reduce advertised rates) and checking pre-approval offers from banks. Also consider hidden costs like optional insurance products often added to dealer finance, and understand that banks generally require stronger credit histories than dealer finance companies. For maximum leverage, secure bank pre-approval before negotiating with dealers—this provides a competitive benchmark and strengthens your position when discussing dealer finance options.'
  },
  {
    id: 'finance-8',
    question: 'What happens if I can\'t make my car finance payments?',
    answer: 'If you anticipate payment difficulties, contact your finance provider immediately—before missing a payment if possible. Most lenders offer temporary solutions for genuine financial hardship, such as payment holidays, reduced payment plans, or extended loan terms to lower monthly payments. If you\'ve already missed payments, expect contact from your lender via phone, email, and formal letters. Missing 1-2 payments typically triggers reminder notices, while 3+ missed payments often result in default notices giving you 14 days to address arrears before further action. Consistently missed payments may lead to vehicle repossession—voluntary surrender (returning the vehicle yourself) causes less damage to your credit score than forced repossession. Even after repossession, you remain liable for any shortfall between the vehicle\'s sale price and your outstanding balance, plus repossession costs. Throughout this process, your credit score will be impacted, with severity increasing with each missed payment. If your situation is ongoing, consider professional advice from organizations like Citizens Advice, StepChange, or National Debtline, who can negotiate with lenders on your behalf and help develop a sustainable repayment plan.'
  }
]; 