import { FAQItem } from '@/lib/faq-search';

// Car Buying and Selling FAQs
export const carBuyingSellingFaqs: FAQItem[] = [
  {
    id: 'buying-selling-1',
    question: 'What is the best time to sell a car in the UK?',
    answer: 'The optimal time to sell a car in the UK depends on various factors. Generally, convertibles and sports cars tend to fetch higher prices in spring and summer when demand increases. Four-wheel drive and SUVs often sell better in autumn and winter. Avoid December if possible, as the market typically slows during the holiday season. January through March can be advantageous for selling newer cars as buyers receive tax refunds and bonuses. For maximum value, sell before major plate changes in March and September, as these introduce newer registrations that can devalue older vehicles. Also consider selling before your car reaches significant mileage milestones (like 100,000 miles) or just before a major service or MOT is due, as these factors can impact resale value.'
  },
  {
    id: 'buying-selling-2',
    question: 'How can I get the best price when selling my car privately?',
    answer: 'To maximise your car\'s selling price in a private sale, start with thorough preparation: professionally clean and detail the vehicle inside and out; address minor cosmetic issues and ensure all features work properly; gather comprehensive service history, previous MOTs, and maintenance records; and consider a fresh MOT even if the current one hasn\'t expired. When advertising, take high-quality photographs from multiple angles in good lighting, write a detailed description highlighting key features and recent work, price competitively based on realistic market research, and list on multiple platforms (Auto Trader, eBay Motors, Gumtree, Facebook Marketplace). During viewings, be transparent about the car\'s history, prepare for test drives (verify viewer\'s licence and insurance), have pricing research available to justify your asking price, and be willing to negotiate while maintaining a firm minimum acceptable price. Consider having the vehicle\'s history report ready to reassure serious buyers.'
  },
  {
    id: 'buying-selling-3',
    question: 'What\'s the difference between part-exchange and selling privately?',
    answer: 'Part-exchanging offers convenience and simplicity—you trade your current vehicle as partial payment for a new one, eliminating the need to advertise, manage viewings, or handle paperwork associated with private sales. The process is typically completed in one transaction, reducing time investment and administrative burden. However, you\'ll generally receive 10-15% less than private sale value. Private selling requires more effort—creating listings, responding to enquiries, arranging viewings, negotiating with buyers, and handling payment and ownership transfer. You\'ll need to manage potential security concerns with strangers visiting your home or meeting in public. While time-consuming and potentially stressful, private sales usually yield higher returns. For unique, collectible, or particularly well-maintained vehicles, this difference can be substantial. Your decision should consider time availability, comfort with the selling process, and whether the potential financial gain outweighs the convenience of part-exchange.'
  },
  {
    id: 'buying-selling-4',
    question: 'How do I negotiate when buying a car from a dealership?',
    answer: 'Effective dealership negotiation requires thorough preparation: research the market value of your target vehicle, identify competitor pricing, understand available trim levels and options, and determine your maximum budget including financing costs. Visit toward month/quarter end when salespeople face targets, and consider less busy weekdays. Begin negotiation from the "out-the-door" price rather than monthly payments. Demonstrate your market knowledge by referencing comparable vehicles, be prepared to walk away, and consider requesting additional value rather than just price reductions (extended warranties, service packages, accessories). For financing, secure pre-approval from external lenders before discussing dealer finance options, allowing you to compare terms. On part-exchanges, negotiate the new car price before discussing your trade-in to prevent combined negotiations that mask the true deal value. Maintain a respectful approach throughout—the goal is a fair deal where both parties feel satisfied.'
  },
  {
    id: 'buying-selling-5',
    question: 'What paperwork do I need to complete when selling my car?',
    answer: 'When selling a car in the UK, you must complete section 6 of the V5C registration document (logbook) with the buyer\'s details, sign section 8, and give the buyer the New Keeper Slip (section 10). You must then send the remaining V5C to the DVLA to inform them of the sale. Additionally, provide a dated receipt containing both parties\' names and addresses, the vehicle details (registration, make, model, VIN), agreed price, and both signatures. Include all service history documents, the current MOT certificate, operation manuals, spare keys, and warranty documentation if applicable. You should also cancel your insurance or transfer it to another vehicle. For added protection, consider using the DVLA\'s online service to immediately notify them of the sale, and keep copies of all documentation. It\'s advisable to complete a sales contract specifying the vehicle is sold "as seen" but accurately described, protecting you from future disputes.'
  },
  {
    id: 'buying-selling-6',
    question: 'Is it better to finance a car or pay cash?',
    answer: 'The decision between financing and cash purchase depends on personal circumstances. Paying cash eliminates interest costs (potentially saving thousands), simplifies the transaction, avoids monthly financial obligations, and gives you immediate equity. However, it significantly depletes savings that might be better used for investments or emergency funds. Financing preserves your cash reserves, may offer promotional rates (sometimes 0% APR), could build credit history through regular payments, and might include valuable manufacturer incentives unavailable to cash buyers. On the downside, you\'ll typically pay interest (increasing the total cost), face approval requirements, and may need comprehensive insurance coverage throughout the loan term. If your cash could earn investment returns exceeding the loan interest rate, or if you need to maintain liquid reserves, financing could be financially advantageous despite the interest cost. Consider your complete financial picture—including emergency savings, investment opportunities, and cash flow—rather than focusing solely on the vehicle\'s price.'
  },
  {
    id: 'buying-selling-7',
    question: 'How do I sell a car with outstanding finance?',
    answer: 'When selling a car with outstanding finance in the UK, you have several options. Ideally, settle the finance before selling by requesting a settlement figure from your lender and paying it off, which gives you clear ownership to transfer to the buyer. If immediate settlement isn\'t possible, use part of the buyer\'s payment to clear the finance during the sale process—contact your finance company for their procedure, as they may facilitate this at their office or through a dealership. For negative equity situations (owing more than the car\'s value), you\'ll need to cover the shortfall yourself before completing the sale. Never sell a financed vehicle without disclosure and finance settlement, as the car legally belongs to the finance company until fully paid. Many buyers check vehicle history which will reveal outstanding finance, and attempting to sell without settling finance constitutes fraud. Some specialised car buying services can handle finance settlement as part of their purchase process, though typically at lower purchase prices.'
  },
  {
    id: 'buying-selling-8',
    question: 'What should I know about buying a car at auction?',
    answer: 'When buying at auction, understand that vehicles are generally sold without warranties and limited inspection opportunities—typically 15-30 minutes before bidding begins. Research thoroughly: register with the auction house beforehand, obtain their catalogue early, inspect vehicles during preview periods, and set a firm maximum bid accounting for buyer\'s fees (typically 5-10% of hammer price), VAT, and potential repair costs. Arrive early on sale day for final inspections, observe initial sales to understand the pace, and maintain disciplined bidding. Most auctions offer condition reports using standardised grading systems, but these aren\'t guarantees—they\'re guides requiring interpretation. Payment terms are strict, usually requiring full settlement within 24 hours. For inexperienced buyers, consider attending several auctions as an observer before participating, and potentially bringing a knowledgeable friend or mechanic during inspections. While auctions can offer good value, they require substantial market knowledge, mechanical understanding, and emotional discipline to avoid costly mistakes.'
  }
]; 