import { getServerSideSitemapIndex } from 'next-sitemap';

// Configure this route as static for compatibility with Vercel deployment
export const dynamic = 'force-static';

// Add cache control for this route (revalidate every 4 hours)
export const revalidate = 14400;

export async function GET() {
  // Base URL for the site - use the production URL in a production environment
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://asmperformancecars.co.uk';
  
  // Create the sitemap index with references to all other sitemaps
  return getServerSideSitemapIndex([
    // Reference to the static sitemap generated by next-sitemap
    `${baseUrl}/static-sitemap.xml`,
    // Reference to the dynamic pages sitemap
    `${baseUrl}/server-sitemap-pages.xml`,
    // Reference to the dynamic car listings sitemap
    `${baseUrl}/server-sitemap-cars.xml`,
    // Reference to the dynamic blog posts sitemap
    `${baseUrl}/server-sitemap-blogs.xml`,
  ]);
} 