// This file is renamed to robots.ts.bak to avoid conflict
// with the robots.txt generated by next-sitemap in the build process
// If you need to enable this file, make sure to disable robots.txt
// generation in next-sitemap.config.js (set generateRobotsTxt: false)

import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL || 'https://asmperformancecars.co.uk';
  
  return {
    rules: {
      userAgent: '*',
      allow: '/',
      disallow: ['/api/*', '/admin/*', '/_next/*'],
    },
    sitemap: `${baseUrl}/sitemap-index.xml`,
  };
} 