import { FAQItem } from '@/lib/faq-search';

// Car Insurance FAQs
export const carInsuranceFaqs: FAQItem[] = [
  {
    id: 'insurance-1',
    question: 'What types of car insurance are available in the UK?',
    answer: 'In the UK, there are three main types of car insurance: Third Party Only (the minimum legal requirement that covers damage to other vehicles, property, and injuries to others, but not your own vehicle); Third Party, Fire and Theft (includes the above plus coverage if your vehicle is stolen or damaged by fire); and Comprehensive (the most extensive coverage, including all third party protection plus damage to your own vehicle regardless of fault, personal injury coverage, and often windscreen repair). Additional coverages that can be added include courtesy car provision, legal expenses coverage, breakdown assistance, personal belongings coverage, and no claims discount protection. The cost varies significantly based on coverage level, with comprehensive typically being the most expensive, though not always. Your choice should balance adequate protection with your budget constraints and the value of your vehicle.'
  },
  {
    id: 'insurance-2',
    question: 'How can I get cheaper car insurance?',
    answer: 'To lower your car insurance premiums, compare quotes from multiple providers using comparison websites as well as direct insurers. Consider increasing your voluntary excess (while ensuring it remains affordable if you need to claim), pay annually rather than monthly to avoid interest charges, and accurately estimate your mileage without overestimating. Choose a car in a lower insurance group, install approved security devices, and park in a secure location overnight. Building a no-claims discount significantly reduces premiums over time, as does adding an experienced second driver (but never falsely listing them as the main driver). Consider specialized policies like black box/telematics insurance, especially for younger drivers, and select only the add-ons you genuinely need. Review potential discounts for professional memberships, dashboard camera usage, or multi-policy arrangements with the same insurer. Finally, ensure your job title accurately reflects your role (while remaining truthful), as slight wording variations can impact premiums.'
  },
  {
    id: 'insurance-3',
    question: 'What is a no-claims bonus and how does it work?',
    answer: 'A no-claims bonus (NCB) or no-claims discount is a reward for not making an insurance claim during your policy period, typically providing a discount on your premium that increases with each consecutive claim-free year. In the UK, the discount generally increases annually for the first 5 years, with reductions of approximately 30% after one year, 40% after two, 50% after three, 60% after four, and up to 70-80% after five or more years. If you make a claim where your insurer pays out, your NCB typically reduces by two years, though this varies by insurer. You can protect your NCB for an additional premium—this doesn\'t prevent premium increases following a claim but preserves your discount percentage. Your NCB belongs to you, not the vehicle, and can usually be transferred between insurers and vehicles, though you generally have two years to use it before it expires. Most insurers require proof of your NCB when switching providers, and while many recognize NCB earned abroad, this varies by company and may require documentation.'
  },
  {
    id: 'insurance-4',
    question: 'Do I need GAP insurance when buying a car?',
    answer: 'GAP (Guaranteed Asset Protection) insurance covers the difference between your car insurance payout (based on current market value) and either the original purchase price or the outstanding finance balance if your vehicle is written off or stolen. This protection is particularly valuable for new cars, which depreciate rapidly—typically 35-40% in the first three years. GAP insurance is most beneficial if: you\'ve purchased a new vehicle with a significant depreciation rate; you\'ve made a small deposit on a finance agreement, creating negative equity; you have outstanding finance exceeding the current vehicle value; or you\'re leasing with substantial early termination fees. It\'s less essential for used vehicles over three years old (which depreciate more slowly), vehicles purchased outright without finance, or when your comprehensive insurance offers "new car replacement" within the first year. GAP insurance costs approximately £100-£300 for three years of coverage, varying based on vehicle value and type of GAP policy (Return to Invoice, Finance GAP, or Vehicle Replacement). Always compare directly from standalone providers rather than accepting dealer offerings, which often carry significant markups.'
  },
  {
    id: 'insurance-5',
    question: 'Is it worth getting black box insurance?',
    answer: 'Black box (telematics) insurance monitors your driving behavior via a device installed in your vehicle or a smartphone app, potentially offering premium reductions of 20-30% for safe drivers. This option is particularly beneficial for: young or new drivers facing high traditional premiums (often saving £400+ annually); safe drivers with other risk factors like age or location; low-mileage drivers (under 7,000 miles annually); and those driving primarily during daylight hours. The technology evaluates factors including speed, acceleration, braking patterns, cornering, time of day, and mileage. Benefits extend beyond potential cost savings to include feedback improving driving habits, theft tracking capabilities, and automated emergency services notification after accidents. However, drawbacks include driving style restrictions (particularly regarding night driving, sharp acceleration, or braking), privacy concerns about location tracking, potential mid-term premium adjustments based on driving behavior, and technical issues with the devices themselves. Installation is typically free, but some providers charge removal fees if you switch insurers. To maximize benefits, understand your provider\'s specific scoring system, drive smoothly and consistently, observe speed limits rigorously, plan journeys to avoid high-risk times, and regularly review your driving feedback.'
  },
  {
    id: 'insurance-6',
    question: 'How does a car insurance excess work?',
    answer: 'Insurance excess is the amount you must pay toward any claim before your insurer covers the remainder. It consists of two parts: the compulsory excess (set by the insurer based on risk factors like your age, driving history, and vehicle type) and the voluntary excess (an additional amount you choose when purchasing the policy). When making a claim, you pay the combined total of both excesses. Higher voluntary excesses generally reduce your premium but increase your out-of-pocket expenses if you claim. For example, with a £250 compulsory and £150 voluntary excess, you\'d pay the first £400 of any claim\'s cost. In non-fault accidents, you initially pay the excess but can often recover it from the at-fault party\'s insurer. For windscreen claims, a separate lower excess typically applies (usually £50-£75). No excess is generally required for third-party claims or fire and theft claims due to recovered stolen vehicles. When selecting your voluntary excess, balance premium savings against affordability in a claim scenario, considering your vehicle\'s value and your financial situation. Some insurers offer excess protection insurance as an add-on, which reimburses your excess payment after a claim for an additional premium.'
  },
  {
    id: 'insurance-7',
    question: 'Can I drive someone else\'s car on my insurance?',
    answer: 'Whether you can drive someone else\'s car using your own insurance depends on your policy\'s Driving Other Cars (DOC) coverage. Traditionally included in comprehensive policies, DOC has become increasingly restricted or eliminated entirely, particularly for drivers under 25 or in high-risk professions. When available, DOC typically provides only third-party coverage (covering damage to other vehicles but not the car you\'re driving), applies only in emergencies rather than regular use, and doesn\'t cover vehicles you own, rent, or lease. To determine if you have DOC, check your certificate of insurance for a section titled "Driving Other Cars" or similar wording, or contact your insurer directly. Alternatives to DOC include: being added as a named driver on the vehicle owner\'s policy (providing the same level of coverage as the main policyholder); purchasing temporary car insurance (available for periods from one hour to 30 days); or arranging Non-Owner Car Insurance for regular driving of others\' vehicles. Driving without proper insurance is illegal and can result in penalty points, fines, and potential vehicle seizure, so always verify coverage before driving someone else\'s car.'
  },
  {
    id: 'insurance-8',
    question: 'What happens to my insurance if I modify my car?',
    answer: 'Vehicle modifications—any changes from the manufacturer\'s standard specification—must be declared to your insurer immediately. Modifications fall into two categories: performance enhancements (engine tuning, exhaust systems, transmission alterations) that typically increase premiums significantly due to perceived higher risk; and cosmetic/comfort modifications (body kits, window tints, entertainment systems) that may increase premiums moderately due to higher repair costs or theft attraction. Some modifications like security improvements or mobility adaptations might actually reduce premiums. Failing to disclose modifications can result in denied claims, policy cancellation, and difficulty obtaining future insurance. When insuring a modified vehicle, specialist insurers often offer better rates than mainstream providers, as they better understand modification impacts and the enthusiast community. If purchasing an already-modified vehicle, obtain detailed documentation of all modifications from the previous owner before seeking insurance. When planning modifications, contact your insurer beforehand to understand premium implications. Most insurers consider even dealer-fitted optional extras as modifications requiring disclosure. If your insurer rejects a planned modification or quotes an unreasonable premium increase, you can seek quotes from alternative providers before proceeding.'
  }
]; 